package com.vikanshu.newsyt

object Constants {
    const val DATABASE_NAME = "Articles_Database"
    val CATEGORIES =
        arrayOf("business", "entertainment", "general", "health", "science", "sports", "technology")
    val COUNTRIES = mapOf(
        "AR" to "Argentina",
        "AU" to "Australia",
        "AT" to "Austria",
        "BE" to "Belgium",
        "BR" to "Brazil",
        "BG" to "Bulgaria",
        "CA" to "Canada",
        "CN" to "China",
        "CO" to "Colombia",
        "CU" to "Cuba",
        "CZ" to "Czechia",
        "EG" to "Egypt",
        "FR" to "France",
        "DE" to "Germany",
        "GR" to "Greece",
        "HK" to "Hong Kong",
        "HU" to "Hungary",
        "IN" to "India",
        "ID" to "Indonesia",
        "IE" to "Ireland",
        "IL" to "Israel",
        "IT" to "Italy",
        "JP" to "Japan",
        "KR" to "Korea (the Republic of)",
        "LV" to "Latvia",
        "LT" to "Lithuania",
        "MY" to "Malaysia",
        "MX" to "Mexico",
        "MA" to "Morocco",
        "NL" to "Netherlands (the)",
        "NZ" to "New Zealand",
        "NG" to "Nigeria",
        "NO" to "Norway",
        "PH" to "Philippines (the)",
        "PL" to "Poland",
        "PT" to "Portugal",
        "RO" to "Romania",
        "RU" to "Russian Federation (the)",
        "SA" to "Saudi Arabia",
        "RS" to "Serbia",
        "SG" to "Singapore",
        "SK" to "Slovakia",
        "SI" to "Slovenia",
        "SE" to "Sweden",
        "CH" to "Switzerland",
        "TH" to "Thailand",
        "TR" to "Turkey",
        "AE" to "United Arab Emirates (the)",
        "GB" to "United Kingdom of Great Britain and Northern Ireland (the)"
    )
}